vich_uploader:
    db_driver: orm

    mappings:
       product_images:
           uri_prefix: /images/product
           upload_destination: '%kernel.project_dir%/public/images/product'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
